services:
  mariadb:
    image: mariadb:11.4
    container_name: bartimaeus-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: bartimaeus_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - internal_net #

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    container_name: bartimaeus-app
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: bartimaeus_db
      DB_PORT: "3306"
    networks:
      - internal_net
    mem_limit: 2g

  screening-router:
    build:
      context: .
      dockerfile: Dockerfile
      target: screening-router
    container_name: bartimaeus-screening-router
    restart: unless-stopped
    ports:
      - "8080:8080" # Sole entry point for external traffic
    networks:
      external_net:
        # External incoming interface (eth0)
        ipv4_address: 10.10.0.2 # 외부 진입 고정 IP
      dmz_net:
        # DMZ forwarding interface (eht1)
        ipv4_address: 10.20.0.2 # DMZ router 고정 IP
    cap_add:
      - NET_ADMIN # Network administration privilege
      - NET_RAW # Raw socket creation privilege
    depends_on:
      - reverse-proxy

  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: reverse-proxy
    container_name: bartimaeus-reverse-proxy
    restart: unless-stopped
    depends_on:
      - app
    environment:
      BACKEND_HOST: app
    networks:
      dmz_net:
        ipv4_address: 10.20.0.3 # DMZ Proxy 고정 IP
      # Forward traffic to backend app
      internal_net:

volumes:
  mariadb_data:

    # 망 분리를 위한 3대 독립 가상 네트워크 정의
networks:
  external_net:
    driver: bridge # Network for incoming external traffic
    ipam:
      config:
        - subnet: 10.10.0.0/24 # Fix external network subnet
  dmz_net:
    driver: bridge # DMZ zone between screening router and reverse proxy
    ipam:
      config:
        - subnet: 10.20.0.0/24 # Fix DMZ network subnet
  internal_net:
    driver: bridge # Internal private network between backend app and DB
